const actionTypes = {
  FETCH_ALL_USERS: "FETCH_ALL_USERS",
  ERROR_FETCHING_ALL_USERS: "ERROR_FETCHING_ALL_USERS", 
  REGISTER_USER: "REGISTER_USER",
  ERROR_REGISTERING_USER: "ERROR_REGISTERING_USER", 
}

export default actionTypes
